# GNU General Public License v3.0+ (see LICENSES/GPL-3.0-or-later.txt or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2025 Felix Fontein <felix@fontein.de>

line-length = 160

[lint]
# https://docs.astral.sh/ruff/rules/

select = ["A", "B", "E", "F", "FA", "FLY", "SIM"]
ignore = [
    # Better keep ignored (for now)
    "E402",  # Module level import not at top of file
    "B904",  # Use raise ... from
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed or starting with dummy
dummy-variable-rgx = "^(_|dummy).*$"

[lint.isort]
known-third-party = [
    "ansible_collections.community.internal_test_tools",
]
